import type { VehicleDataBroker } from '../vss/databroker';

/**
 * A third-party vehicle app, modelled on Eclipse Velocitas: it only knows VSS paths
 * and the broker API, never which ECU or simulator sits underneath.
 */
export interface VehicleApp {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  /** Starts the app; returns a function that stops it. */
  start(broker: VehicleDataBroker): () => void;
}

/** Holds app instances and starts/stops them against one broker. */
export class AppRuntime {
  private readonly running = new Map<string, () => void>();
  private readonly listeners = new Set<() => void>();
  readonly apps: VehicleApp[];

  constructor(private readonly broker: VehicleDataBroker, apps: readonly VehicleApp[]) {
    this.apps = [...apps];
  }

  /** Adds an app at runtime (e.g. one generated by Claude) and starts it. */
  add(app: VehicleApp): void {
    this.apps.push(app);
    this.setRunning(app.id, true);
    this.notify();
  }

  remove(id: string): void {
    this.setRunning(id, false);
    const i = this.apps.findIndex((a) => a.id === id);
    if (i >= 0) this.apps.splice(i, 1);
    this.notify();
  }

  onChange(cb: () => void): () => void {
    this.listeners.add(cb);
    return () => this.listeners.delete(cb);
  }

  private notify(): void {
    this.listeners.forEach((cb) => cb());
  }

  isRunning(id: string): boolean {
    return this.running.has(id);
  }

  setRunning(id: string, run: boolean): void {
    if (run === this.isRunning(id)) return;
    if (run) {
      const app = this.apps.find((a) => a.id === id);
      if (!app) throw new Error(`Unknown app ${id}`);
      this.running.set(id, app.start(this.broker));
    } else {
      this.running.get(id)?.();
      this.running.delete(id);
    }
    this.notify();
  }
}
