"""Generates a virtual-ECU skeleton from an AUTOSAR system description (ARXML).

Takes the ARXML your AUTOSAR authoring tool exports (e.g. ETAS ISOLAR-A/AB) and, for one ECU,
writes everything needed to run it as a vECU in this simulator:

  <out>/<cluster>.dbc            the bus as DBC (cantools, candump, the CAN provider)
  <out>/<ecu>_com.py             COM configuration for the ECU: Tx/Rx frames, signal constants
                                 with units/ranges, enums for value tables, a Com subclass
  <out>/vss_dbc.<ecu>.json       VSS <-> DBC mapping for the CAN provider; signals already in
                                 --mapping are carried over, the rest are TODO entries
  <out>/<ecu>_swc_template.py    application skeleton (one handler per received frame); copy it
                                 and fill in the logic

    python arxml2vecu.py arxml/sim_body.arxml --ecu BCM --out generated --mapping mapping/vss_dbc.json

ARXML is read with canmatrix, which accepts the AUTOSAR 3 and 4 variants written by common
tools. Frames are named after their frame triggering (falling back to the frame name).
"""

from __future__ import annotations

import argparse
import io
import json
import keyword
import re
import sys
from pathlib import Path

import canmatrix
import canmatrix.formats
import cantools


def ident(name: str) -> str:
    out = re.sub(r"\W", "_", name)
    if out[0].isdigit() or keyword.iskeyword(out):
        out = f"_{out}"
    return out


def class_name(name: str) -> str:
    """BCM_BrakeLampStatus -> BcmBrakeLampStatus (keeps inner CamelCase, tames ALLCAPS parts)."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]", name) if p]
    return "".join(p.capitalize() if p.isupper() or p.islower() else p[0].upper() + p[1:] for p in parts) or "Ecu"


def load_cluster(path: str, cluster: str | None) -> tuple[str, canmatrix.CanMatrix]:
    clusters = canmatrix.formats.loadp(path)
    if not clusters:
        sys.exit(f"No CAN cluster found in {path}")
    if cluster is None:
        if len(clusters) > 1:
            sys.exit(f"Several clusters in {path}: {', '.join(clusters)}; pick one with --cluster")
        cluster = next(iter(clusters))
    matrix = clusters[cluster]
    for frame in matrix.frames:  # name frames after their triggering, e.g. FRAME_X -> X
        frame.name = frame.attributes.get("FrameTriggeringName") or re.sub(r"^FRAME_", "", frame.name)
    return cluster, matrix


def write_dbc(matrix: canmatrix.CanMatrix, path: Path) -> cantools.database.can.Database:
    buf = io.BytesIO()
    canmatrix.formats.dump(matrix, buf, "dbc")
    path.write_bytes(buf.getvalue())
    db = cantools.database.load_file(str(path))
    return db


def signal_doc(sig) -> str:
    parts = []
    if sig.unit:
        parts.append(sig.unit)
    if sig.minimum is not None and sig.maximum is not None:
        parts.append(f"{sig.minimum:g}..{sig.maximum:g}")
    if sig.scale != 1 or sig.offset != 0:
        parts.append(f"raw*{sig.scale:g}{'+' if sig.offset >= 0 else ''}{sig.offset:g}")
    if sig.comment:
        parts.append(sig.comment)
    return ", ".join(parts)


def generate_com(db, ecu: str, cluster: str, arxml: str, dbc_name: str) -> str:
    tx = [m for m in db.messages if ecu in m.senders]
    rx = [m for m in db.messages if ecu not in m.senders and any(ecu in s.receivers for s in m.signals)]
    lines = [
        f'"""COM configuration for ECU {ecu} on cluster {cluster}.',
        "",
        f"GENERATED by arxml2vecu.py from {arxml} - do not edit; regenerate instead.",
        '"""',
        "",
        "from enum import IntEnum",
        "from pathlib import Path",
        "",
        "from com_runtime import Com",
        "",
        f'DBC_PATH = str(Path(__file__).with_name("{dbc_name}"))',
        "",
    ]
    for title, messages in (("Transmitted", tx), ("Received", rx)):
        lines.append(f"# --- {title} frames {'-' * 60}"[:96])
        for m in messages:
            lines.append(f"# 0x{m.frame_id:03X} {m.name}: {m.length} bytes, cycle {m.cycle_time or 'event'} ms, from {'/'.join(m.senders) or '?'}")
            for s in m.signals:
                doc = signal_doc(s)
                lines.append(f'{ident(s.name)} = "{s.name}"{f"  # {doc}" if doc else ""}')
            lines.append("")
    for m in tx + rx:
        for s in m.signals:
            if not s.choices:
                continue
            lines.append(f"class {class_name(s.name)}(IntEnum):")
            lines.append(f'    """Value table of {s.name}."""')
            for raw, name in sorted(s.choices.items()):
                lines.append(f"    {ident(str(name))} = {raw}")
            lines.append("")
    lines += [
        "",
        f"class {class_name(ecu)}Com(Com):",
        f'    """Signal-level COM for {ecu}: Tx {", ".join(m.name for m in tx) or "-"}; Rx {", ".join(m.name for m in rx) or "-"}."""',
        "",
        f'    NODE = "{ecu}"',
        "    DBC_PATH = DBC_PATH",
        "",
    ]
    return "\n".join(lines)


def generate_template(db, ecu: str) -> str:
    rx = [m for m in db.messages if ecu not in m.senders and any(ecu in s.receivers for s in m.signals)]
    tx = [m for m in db.messages if ecu in m.senders]
    mod = f"{ecu.lower()}_com"
    cls = f"{class_name(ecu)}Com"
    handlers = []
    for m in rx:
        sigs = ", ".join(s.name for s in m.signals)
        handlers += [
            f"    def on_{ident(m.name).lower()}(self, values: dict) -> None:",
            f'        """0x{m.frame_id:03X} {m.name}: {sigs}."""',
            "        # TODO: application logic; write outputs with self.com.write(SIGNAL, value)",
            "",
        ]
    tx_signals = ", ".join(s.name for m in tx for s in m.signals)
    return "\n".join([
        f'"""{ecu} application (software component) - template generated by arxml2vecu.py.',
        "",
        "Copy this file next to the generated COM module, fill in the handlers, and run it:",
        f"    python {ecu.lower()}_swc.py --interface udp_multicast",
        f"Outputs ({ecu} sends): {tx_signals or '-'}",
        '"""',
        "",
        "import argparse",
        "import logging",
        "import sys",
        "import time",
        "from pathlib import Path",
        "",
        "sys.path.insert(0, str(Path(__file__).resolve().parent.parent))  # com_runtime, canbus",
        "",
        "from canbus import add_bus_arguments, open_bus",
        f"from {mod} import *  # noqa: F401,F403 - signal names and value tables",
        f"from {mod} import {cls}",
        "",
        "",
        f"class {class_name(ecu)}:",
        "    def __init__(self, com):",
        "        self.com = com",
        "        com.on_receive(self.dispatch)",
        "",
        "    def dispatch(self, message: str, values: dict) -> None:",
        "        handler = getattr(self, f\"on_{message.lower()}\", None)",
        "        if handler:",
        "            handler(values)",
        "",
        *handlers,
        "",
        "def main() -> None:",
        "    parser = argparse.ArgumentParser()",
        "    add_bus_arguments(parser)",
        "    args = parser.parse_args()",
        "    logging.basicConfig(level=logging.INFO)",
        f"    com = {cls}(open_bus(args.interface, args.channel))",
        f"    {class_name(ecu)}(com)",
        "    com.start()",
        "    while True:",
        "        time.sleep(1)",
        "",
        "",
        'if __name__ == "__main__":',
        "    main()",
        "",
    ])


def generate_mapping(db, ecu: str, existing: dict) -> tuple[dict, int, int]:
    """VSS mapping for the CAN provider: reuse known entries, TODO for the rest."""
    by_signal: dict[str, list[tuple[str, str, dict]]] = {}
    for path, spec in existing.items():
        for direction in ("dbc2vss", "vss2dbc"):
            if direction in spec:
                by_signal.setdefault(spec[direction]["signal"], []).append((path, direction, spec[direction]))
    mapping: dict[str, dict] = {}
    reused = todo = 0
    for m in db.messages:
        if ecu in m.senders:
            direction = "dbc2vss"  # the ECU reports it: CAN -> VSS
        elif any(ecu in s.receivers for s in m.signals):
            direction = "vss2dbc"  # the ECU needs it: VSS -> CAN
        else:
            continue
        for s in m.signals:
            if s.name.endswith("Counter"):
                continue  # protocol detail, handled by the provider
            known = [k for k in by_signal.get(s.name, []) if k[1] == direction]
            if known:
                for path, d, spec in known:
                    mapping.setdefault(path, {})[d] = spec
                reused += 1
            else:
                entry = {"signal": s.name}
                if s.choices:
                    entry["transform"] = {"mapping": [{"from": str(v) if direction == "dbc2vss" else "TODO", "to": "TODO" if direction == "dbc2vss" else str(v)} for v in s.choices.values()]}
                mapping[f"TODO.{s.name}"] = {direction: entry}
                todo += 1
    return dict(sorted(mapping.items())), reused, todo


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a vECU skeleton from AUTOSAR ARXML")
    parser.add_argument("arxml", help="AUTOSAR system description (.arxml)")
    parser.add_argument("--ecu", required=True,
                        help="ECU to simulate as vECU, e.g. BCM; the CAN provider plays the rest of the bus")
    parser.add_argument("--cluster", help="CAN cluster, if the ARXML has several")
    parser.add_argument("--out", default="generated", help="output directory")
    parser.add_argument("--mapping", help="existing vss_dbc.json whose entries should be reused")
    args = parser.parse_args()

    cluster, matrix = load_cluster(args.arxml, args.cluster)
    ecus = [e.name for e in matrix.ecus]
    if args.ecu not in ecus:
        sys.exit(f"ECU {args.ecu!r} not in cluster {cluster}; ECUs: {', '.join(ecus)}")
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    dbc_name = f"{ident(cluster).lower()}.dbc"
    db = write_dbc(matrix, out / dbc_name)
    ecu_mod = args.ecu.lower()
    (out / f"{ecu_mod}_com.py").write_text(generate_com(db, args.ecu, cluster, Path(args.arxml).name, dbc_name))
    (out / f"{ecu_mod}_swc_template.py").write_text(generate_template(db, args.ecu))
    existing = json.loads(Path(args.mapping).read_text()) if args.mapping else {}
    mapping, reused, todo = generate_mapping(db, args.ecu, existing)
    (out / f"vss_dbc.{ecu_mod}.json").write_text(json.dumps(mapping, indent=2) + "\n")

    tx = [m for m in db.messages if args.ecu in m.senders]
    rx = [m for m in db.messages if args.ecu not in m.senders and any(args.ecu in s.receivers for s in m.signals)]
    print(f"cluster {cluster}: {len(db.messages)} frames, ECUs {', '.join(ecus)}")
    print(f"{args.ecu}: sends {', '.join(f'{m.name}({m.cycle_time or 0}ms)' for m in tx) or '-'}; "
          f"receives {', '.join(m.name for m in rx) or '-'}")
    print(f"wrote {out}/: {dbc_name}, {ecu_mod}_com.py, {ecu_mod}_swc_template.py, vss_dbc.{ecu_mod}.json "
          f"({reused} signals mapped from --mapping, {todo} TODO)")


if __name__ == "__main__":
    main()
